### ISSUE TITLE
Possibly look into using a wrapper library for talking to forecast.io

### ISSUE THREAD

**Issue by EdHurtig** [jeffbyrnes/hubot-forecast#13]
There are several node.js wrapper libraries built for Forecast.io which might be useful:

not a major thing, just saw the wrappers and thought it would be worth sharing

https://developer.forecast.io/docs/v2

**Comment by jeffbyrnes** [comment]
@EdHurtig as I mentioned in #14 & #3, I’m actually partway through with a refactor, and it does exactly this. Thanks for thinking of this!
