### ISSUE TITLE
Want to test weather warning in room

### ISSUE THREAD

**Issue by TheReal1604** [jeffbyrnes/hubot-forecast#17]
Hey,

is there a command to test the weather warning in the configured room? The command "bot weather" works fine, but the automatic warning in the room not. Now i can not reproduce the issue because i dont know when the bot posts a message in this room.

I try to implement your script in my Docker Rocket.Chat Hubot deployment.

Thx in advance!

Greetings

**Comment by jeffbyrnes** [comment]
@TheReal1604 it’s very possible, in its current state, that the warning isn’t working. If you can tail the logs for your Hubot, you should see some log messages for when the weather warning starts up, and checks the weather. That’s where you’d start to see what’s not working with.

**Comment by TheReal1604** [comment]
@jeffbyrnes: I got this in my log:

> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Wed Feb 03 2016 10:46:41 GMT+0000 (UTC)] INFO Message received with ID eNCbYGzCA5WjnoNpM
> [Wed Feb 03 2016 10:46:41 GMT+0000 (UTC)] INFO Message receive callback id GwZitDqzutGKRXDS5 ts Wed Feb 03 2016 10:46:41 GMT+0000 (UTC)
> [Wed Feb 03 2016 10:46:41 GMT+0000 (UTC)] INFO [Incoming] brian: ship it
> [Wed Feb 03 2016 10:46:41 GMT+0000 (UTC)] INFO Message sent to hubby brain.
> [Wed Feb 03 2016 10:46:41 GMT+0000 (UTC)] INFO Sending Message To Room: KeSeYkZLeQw3wt2NEm8rCjH965b9jTqF64
> [Wed Feb 03 2016 10:46:41 GMT+0000 (UTC)] INFO Message received with ID K2acnCpfs3E6rD6Lt
> [Wed Feb 03 2016 10:46:41 GMT+0000 (UTC)] INFO Message received with ID vuCTYJNN6znK5AKDj
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags
> [Forecast] Requesting forecast data: https://api.forecast.io/forecast/8cfffb9b93f03bd49737aecbbabe56f1/51.339695,12.373075?units=si&exclude=flags

And "Sleeping" at the configured times..

Why it´s actually not working? not complete implemented?

**Comment by jeffbyrnes** [comment]
@TheReal1604 I did some refactoring a while ago, looks like I broke it. :disappointed: Not sure when I'll circle back to this, any help is welcome!

**Comment by TheReal1604** [comment]
@jeffbyrnes Oh nooooo..... sry. i got absolutly no experience with coffeescript :(. (or something like this complex in developing) Hope you can fix this soon. Your script is (on npm) the first that give me this functionality.

**Comment by jeffbyrnes** [comment]
Me too! I really like this module, so getting it working is definitely something I’ll work out. I’ll let you know!
