### ISSUE TITLE
Easier selection of minimum weather threshold

### ISSUE THREAD

**Issue by farski** [jeffbyrnes/hubot-forecast#2]
I can't remember what point my version was at when I blogged about it, but at some point it was definitely too aggressive. I think probably the default needs to be higher (probably what forecast calls "moderate"), and maybe also an ability to set the threshold from the room

**Comment by jeffbyrnes** [comment]
@farski great thoughts, thanks! And yeah, I might set the threshold a bit higher; setting it from the room will require some stronger interaction with Hubot’s “brain”.
