### ISSUE TITLE
Customizable sleep cycles

### ISSUE THREAD

**Issue by farski** [jeffbyrnes/hubot-forecast#4]
The sleep mode for this which prevents messaging during non-work hours is pretty basic and likely not suitable for everyone. Worth brainstorming some ideas for how to make that easier to configure.

**Comment by jeffbyrnes** [comment]
For this one, I might suggest it just be set via EnvVar(s), since it's unlikely to change all that often, as this alert is most useful for an office in a single city/region. That way it’s configurable, but won’t be lost if the Redis brain is wiped for some reason.
